website/models.py
from . import db 
from flask_login import UserMixin
from sqlalchemy.sql import func

class Customer(UserMixin, db.Model):
    nid = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(100))
    name = db.Column(db.String(100))
    user_type = db.Column(db.String(100), default='customer')
    balance = db.Column(db.Integer)
    def get_id(self):
        return (self.email)

class Admin(UserMixin, db.Model):
    nid = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(100))
    name = db.Column(db.String(100))
    user_type = db.Column(db.String(100), default='admin')
    balance = db.Column(db.Integer, default=0)
    def get_id(self):
        return (self.email)
    
class Products(db.Model):
    product_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    product_name = db.Column(db.String(100))
    product_amount = db.Column(db.Integer)
    product_description = db.Column(db.String(100))
    product_rating = db.Column(db.String(100), default='5')
    product_price = db.Column(db.String(100))

class Payment(db.Model):
    payment_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    payment_amount = db.Column(db.Integer)
    payment_coupon = db.Column(db.String(100))
    
class Coupon(db.Model):
    coupon_id = db.Column(db.Integer, primary_key=True, autoincrement=True)
    coupon_name = db.Column(db.String(100))
    coupon_amount = db.Column(db.Integer)
    
class Cart(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    product = db.Column(db.Integer)

website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager
from flask_migrate import Migrate
# from flask_mail import Mail, Message

db = SQLAlchemy()
DB_NAME = "database.db"


def create_app():
    app = Flask(__name__, 
                static_url_path='/',
                static_folder='static',
                template_folder='templates',
                )

    app.config['SECRET_KEY'] = 'SADMAN420'
    app.config['SQLALCHEMY_DATABASE_URI'] = f"mysql+pymysql://root@localhost/sadman"
    db.init_app(app)
    migrate = Migrate(app, db)
    migrate.init_app(app, db)
    
    from .views import views

    app.register_blueprint(views, url_prefix='/')

    from .models import Admin, Customer, Payment, Coupon
    
    with app.app_context():
        db.create_all()
    
    login_manager = LoginManager()
    login_manager.login_view = 'views.login'
    login_manager.init_app(app)
    
    @login_manager.user_loader
    def load_user(email):
        user = Customer.query.filter_by(email=email).first()
        if user:
            print(user)
            return user
        else:
            user = Admin.query.filter_by(email=email).first()
            print("Admin", user)
            return user

    return app

website/views.py
from flask import Blueprint,render_template,redirect,url_for,request, flash
from .models import *
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
views = Blueprint('views', __name__)

@views.route('/', methods=['GET', 'POST'])  
def home():
    products = Products.query.all()
    if request.method=='POST':
        search = request.form.get('search')
        products = Products.query.filter(Products.product_name.like(f'%{search}%')).all()
        return render_template('sadman.html', products=products)
    return render_template("sadman.html", products=products)

@views.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        print(request.form)
        email = request.form.get('email')
        password = request.form.get('password')
        user_type = request.form.get('user_type') 
        print(email, password)
        if user_type.lower() == "admin":
            user = Admin.query.filter_by(email=email).first()
        if user_type.lower() == "customer":
            user = Customer.query.filter_by(email=email).first()
        if user:
            print("USER:",user)
            if check_password_hash(user.password, password):
                print("Logged in")
                login_user(user, remember=True)
                return redirect(url_for('views.home'))
            else:
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')
    return render_template("login.html")



@views.route('/signup', methods=['GET', 'POST'])
def signup():
    if request.method == 'POST':
        print(request.form)
        email = request.form.get('email')
        password = request.form.get('password')
        user_type = request.form.get('user_type').lower()
        if user_type.lower() == "admin":
            new_user = Admin(
                name = request.form.get('name'),
                email=email, 
                password=generate_password_hash(password, method='sha256'),
                user_type = 'admin',
                )
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            return redirect(url_for('views.home'))
        if user_type.lower() == "customer":
            new_user = Customer(
                nid = request.form.get('id'),
                name = request.form.get('name'),
                email=email, 
                password=generate_password_hash(password, method='sha256'),
                user_type = 'customer',
                )
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            return redirect(url_for('views.home'))

    return render_template("signup.html")

@views.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('views.login'))

@views.route('/addproduct', methods=['GET', 'POST'])
def addproduct():
    if request.method == 'POST':
        print(request.form)
        product_amt = request.form.get('product_amt')
        product_name = request.form.get('product_name')
        product_description = request.form.get('product_desc')
        product_price = request.form.get('product_price')
        new_product = Products(
            product_amount=product_amt,
            product_name=product_name,
            product_description=product_description,
            product_price=product_price,
            )
        db.session.add(new_product)
        db.session.commit()
        return redirect(url_for('views.home'))
    return render_template("addproduct.html")

@views.route('/removeproduct', methods=['GET', 'POST'])
def removeproduct():
    if request.method == 'POST':
        print(request.form)
        product_id = request.form.get('product_id')
        product = Products.query.filter_by(product_id=product_id).first()
        db.session.delete(product)
        db.session.commit()
        return redirect(url_for('views.home'))
    return render_template("deleteproduct.html")

@views.route('/makepayment', methods=['GET', 'POST'])
def makepayment():
    if request.method == 'POST':
        print(request.form)
        amt = request.form.get('payamt')
        user = Customer.query.filter_by(email=current_user.email).first()
        if user is None:
            user = Admin.query.filter_by(email=current_user.email).first()
        
        user.balance = user.balance + int(amt)
        db.session.commit()
        return redirect(url_for('views.home'))
    return render_template("payment.html")

@views.route('/cart', methods=['POST', 'GET'])
def cart():
    # if request.method=='POST':
    product = Products.query.first()
    cart = Cart(product=product.product_id)
    db.session.add(cart)
    db.session.commit()
    return render_template('cart.html', product=product)

@views.route('/headphone', methods=['POST', 'GET'])
def headphone():
    products = Products.query.filter(Products.product_name.like('%headphone%')).all()
    return render_template('sadman.html', products=products)

@views.route('/monitor', methods=['POST', 'GET'])
def monitor():
    products = Products.query.filter(Products.product_name.like('%monitor%')).all()
    return render_template('sadman.html', products=products)

@views.route('/mouse', methods=['POST', 'GET'])
def mouse():
    products = Products.query.filter(Products.product_name.like('%mouse%')).all()
    return render_template('sadman.html', products=products)

@views.route('/keyboard', methods=['POST', 'GET'])
def keyboard():
    products = Products.query.filter(Products.product_name.like('%keyboard%')).all()
    return render_template('sadman.html', products=products)

website/templates/addcoupon.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Sadman Store</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <style>
  .fakeimg {
    height: 200px;
    background: #aaa;
  }
  </style>
</head>
<body>

<div class="p-0 bg-secondary text-white text-center" style="background-color: #90bfe1;">
  <h1>Sadman Store</h1>
  <p>CSE 470 Project</p> 
</div>

<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #85c1ec;">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="#">Sign up</a>
          </li>
          
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="./payment.html">Make Payment</a>
          </li>
        <form class="d-flex">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>
  <!--Main layout-->
  <main class="my-5">
    <div class="container" style="width: 500px;">
      <div class="text-center mb-4">
        <h3>Add Discount Coupon</h3>
      </div>
      <form action="" method="">
        <div class="d-flex flex-row align-items-center mb-4 pb-1">
            <div class="flex-fill mx-3">
                <div name="payamt" class="form-outline" style="margin-top: 30px; padding: 6px;">
                  <label class="form-label" for="formControlLgXc">Amount:</label>
                    <input name="payamt" type="text" id="formControlLgXc"
                        class="form-control form-control-lg" value="100"/>
                </div>
  
                <div name="payamt" class="form-outline" style="margin-top: 30px; padding: 6px;">
                  <label class="form-label" for="formControlLgXc">Coupon Code:</label>
                    <input name="payamt" type="text" id="formControlLgXc"
                        class="form-control form-control-lg" value="SADMANSTORE100"/>
                </div>

            </div>
            
        </div>
        <div class="row">
            <div class="col text-center">
                <button type="submit" class="btn btn-outline-info btn-lg">Add Coupon</button>
            </div>
          </div>
      </form>
    </main>
    

</body>
</html>

website/templates/addproduct.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Sadman Store</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <style>
  .fakeimg {
    height: 200px;
    background: #aaa;
  }
  </style>
</head>
<body>

<div class="p-0 bg-secondary text-white text-center" style="background-color: #90bfe1;">
  <h1>Sadman Store</h1>
  <p>CSE 470 Project</p> 
</div>
<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #85c1ec;">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Home</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Login</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Sign up</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="./payment.html">Make Payment</a>
        </li>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>
<!--Main layout-->
<main class="my-5">
  <div class="container">
      <h1>Add Product</h1>
      <!--Section: Content-->
      <form method="post">
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Product ID:</label>
          <input type="text" name="" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Product Name:</label>
          <input type="text" name="product_name" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Description:</label>
          <input type="text" name="product_desc" class="form-control" id="exampleInputPassword1">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Amount:</label>
          <input type="text" name="product_amt" class="form-control" id="exampleInputPassword1">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Price:</label>
          <input type="text" name="product_price" class="form-control" id="exampleInputPassword1">
        </div>
        <div class="mb-3 form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Confirm?</label>
        </div>
        <button type="submit" class="btn btn-primary">Add Product</button><br><br>
        <h5> 
          <a href="./deleteproduct.html">Delete Product?</a>
        </h5>
      </form>
    </div>
  </main>
</body>
</html>

website/templates/cart.html
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/jquery.dataTables.min.css">

<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.js"></script>

<script type="text/javascript" charset="utf8" src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script type="text/javascript" charset="utf8"
    src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" charset="utf8"
    src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>
<script type="text/javascript" charset="utf8"
    src="https://cdn.datatables.net/scroller/2.0.7/js/dataTables.scroller.min.js"></script>
<link rel="stylesheet" type="text/css"
    href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/5.2.0/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.13.1/css/dataTables.bootstrap5.min.css">


<section class="vh-100" style="background-color: #fdccbc;">
    <div class="container h-100">
        <div class="row d-flex justify-content-center align-items-center h-100">
            <div class="col">
                <p><span class="h2">Shopping Cart </span><span class="h4">(1 item in your cart)</span></p>

                <div class="card mb-4">
                    <div class="card-body p-4">

                        <div class="row align-items-center">
                            <div class="col-md-2">
                                <img src="https://mdbcdn.b-cdn.net/img/Photos/Horizontal/E-commerce/Products/1.webp"
                                    class="img-fluid" alt="Generic placeholder image">
                            </div>
                            <div class="col-md-2 d-flex justify-content-center">
                                <div>
                                    <p class="small text-muted mb-4 pb-2">Name</p>
                                    <p class="lead fw-normal mb-0">{{product.product_name}}</p>
                                </div>
                            </div>
                            <div class="col-md-2 d-flex justify-content-center">
                                <div>
                                    <p class="small text-muted mb-4 pb-2">Rating</p>
                                    <p class="lead fw-normal mb-0"><i class="fas fa-circle me-2"
                                            style="color: #fdd8d2;"></i>
                                        {{product.product_rating}}</p>
                                </div>
                            </div>
                            <div class="col-md-2 d-flex justify-content-center">
                                <div>
                                    <p class="small text-muted mb-4 pb-2">Quantity</p>
                                    <p class="lead fw-normal mb-0">1</p>
                                </div>
                            </div>
                            <div class="col-md-2 d-flex justify-content-center">
                                <div>
                                    <p class="small text-muted mb-4 pb-2">Price</p>
                                    <p class="lead fw-normal mb-0">{{product.product_price}}</p>
                                </div>
                            </div>
                            <div class="col-md-2 d-flex justify-content-center">
                                <div>
                                    <p class="small text-muted mb-4 pb-2">Total</p>
                                    <p class="lead fw-normal mb-0">{{product.product_price}}</p>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>

                <div class="card mb-5">
                    <div class="card-body p-4">

                        <div class="float-end">
                            <p class="mb-0 me-5 d-flex align-items-center">
                                <span class="small text-muted me-2">Order total:</span> <span
                                    class="lead fw-normal">{{product.product_price}}</span>
                            </p>
                        </div>

                    </div>
                </div>

                <div class="d-flex justify-content-end">
                    <a type="button" class="btn btn-light btn-lg me-2" href="{{url_for('views.home')}}">Continue shopping</a>
                    <a href="{{url_for('views.makepayment')}}" type="button" class="btn btn-primary btn-lg">Go to Payment</a>
                </div>

            </div>
        </div>
    </div>
</section>

website/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Sadman Store</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <style>
  .fakeimg {
    height: 200px;
    background: #aaa;
  }
  </style>
</head>
<body>

<div class="p-0 bg-secondary text-white text-center" style="background-color: #90bfe1;">
  <h1>Sadman Store</h1>
  <p>CSE 470 Project</p> 
</div>
<!--Main layout-->
<main class="my-5">
  <div class="container">
      <h1>Login</h1>
      <!--Section: Content-->
      <form method="POST">
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">Email address</label>
          <input type="email" name="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
          <div id="emailHelp" class="form-text">We'll never share your email with anyone else.</div>
        </div>
        <div class="mb-3">
          <label for="exampleInputEmail1" class="form-label">user_type</label>
          <input type="text" name="user_type" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
        </div>
        <div class="mb-3">
          <label for="exampleInputPassword1" class="form-label">Password</label>
          <input type="password" name="password" class="form-control" id="exampleInputPassword1">
        </div>
        <div class="mb-3 form-check">
          <input type="checkbox" class="form-check-input" id="exampleCheck1">
          <label class="form-check-label" for="exampleCheck1">Check me out</label>
        </div>
        <button type="submit" class="btn btn-primary">Login</button>
        <button type="submit" class="btn btn-outline-success">
         <a href="{{url_for('views.signup')}}">Sign Up</a> 
      </button>
      </form>
    </div>
  </main>
</body>
</html>

website/templates/sadman.html
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Sadman Store</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  <style>
  .fakeimg {
    height: 200px;
    background: #aaa;
  }
  </style>
</head>
<body>

<div class="p-0 bg-secondary text-white text-center" style="background-color: #90bfe1;">
  <h1>Sadman Store</h1>
  <p>CSE 470 Project - {{current_user}}</p> 
</div>

<nav class="navbar navbar-expand-lg navbar-light bg-light" style="background-color: #85c1ec;">
    <div class="container-fluid">
      <a class="navbar-brand" href="{{url_for('views.home')}}">Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll" aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarScroll">
        <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{url_for('views.login')}}">Login</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{url_for('views.signup')}}">Sign up</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{{url_for('views.makepayment')}}">Make Payment</a>
          </li>
          {% if current_user.user_type == "admin" %}
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{url_for('views.addproduct')}}">Add Product</a>
            </li>
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{{url_for('views.removeproduct')}}">Remove Product</a>
            </li>
            {% endif %}
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="./offer.html">Offer Products</a>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Categories
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
              <li><a class="dropdown-item" href="{{url_for('views.headphone')}}">Headphones</a></li>
              <li><a class="dropdown-item" href="{{url_for('views.monitor')}}">Monitors</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="{{url_for('views.mouse')}}">Mouse</a></li>
              <li><a class="dropdown-item" href="{{url_for('views.keyboard')}}">Keyboard</a></li>
              <li><a class="dropdown-item" href="#">Speaker</a></li>
              <li><a class="dropdown-item" href="{{url_for('views.logout')}}">Logout</a></li>
            </ul>
          </li>
        <form class="d-flex" method="post">
          <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">
          <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
      </div>
    </div>
  </nav>



  <!--Main layout-->
  <main class="my-5">
    <div class="container">
      <!--Section: Content-->
      <section class="text-center">
        <h4 class="mb-5"><strong>Products</strong></h4>

        <div class="row">

          <!-- ITERATOR --> <!-- ITERATOR --><!-- ITERATOR --><!-- ITERATOR --><!-- ITERATOR -->
          {% for product in products %}
          <div class="col-lg-4 col-md-6 mb-4">
            <div class="card">
              <div class="bg-image hover-overlay ripple" data-mdb-ripple-color="light">
                <img src="https://mdbootstrap.com/img/new/standard/nature/035.jpg" class="img-fluid" />
                <a href="#!">
                  <div class="mask" style="background-color: rgba(251, 251, 251, 0.15);"></div>
                </a>
              </div>
              <div class="card-body">
                <h5 class="card-title">{{product.product_name}}</h5>
                <p class="card-text">
                  {{product.des}}
                </p>
                <a href="#!" class="btn btn-primary">{{product.product_price}}</a>
                <a href="{{url_for('views.cart')}}" class="btn btn-primary">Add to Cart</a>
              </div>
            </div>
          </div>
          {% endfor %}
          <!-- ITERATOR --><!-- ITERATOR --><!-- ITERATOR --><!-- ITERATOR --><!-- ITERATOR -->

        </div>
      </section> <br><br> <hr><hr><hr>
      <!-- Footer -->
<footer class=" text-center " style="background-color:#b0f2e5;">
  <h2>About Us</h2>
  <!-- Grid container -->
  <div class="container p-4">
    <!-- Section: Social media -->
    <section class="mb-4">
      <!-- Facebook -->
      <a class="btn btn-primary btn-floating m-1" style="background-color: #3b5998" href="#!" role="button"><i class="fab fa-facebook-f"></i></a>

      <!-- Twitter -->
      <a class="btn btn-primary btn-floating m-1" style="background-color: #55acee" href="#!" role="button"><i class="fab fa-twitter"></i></a>

      <!-- Google -->
      <a class="btn btn-primary btn-floating m-1" style="background-color: #dd4b39" href="#!" role="button"><i class="fab fa-google"></i></a>

      <!-- Instagram -->
      <a class="btn btn-primary btn-floating m-1" style="background-color: #ac2bac" href="#!" role="button"><i class="fab fa-instagram"></i></a>

      <!-- Linkedin -->
      <a class="btn btn-primary btn-floating m-1" style="background-color: #0082ca" href="#!" role="button"><i class="fab fa-linkedin-in"></i></a>
      <!-- Github -->
      <a class="btn btn-primary btn-floating m-1" style="background-color: #333333" href="#!" role="button"><i class="fab fa-github"></i></a>
    </section>
    <!-- Section: Social media -->



    <!-- Section: Text -->
    <section class="mb-4">
      <p>
        I am Sadman Shoumik
      </p>
    </section>
    <!-- Section: Text -->


  </div>
  <!-- Grid container -->

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2)">
    © 2022 Copyright:
    <a class="text-dark" href="">SadmanShoumik.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->
    </div>
  </main>
</body>
</html>